version: '3.7'

networks:
  github:
    name: github
    driver: bridge

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOSTS=mysql
      - UPLOAD_LIMIT=300M
    ports:
      - ${PMA_PORT:-9000}:80
    networks:
      - github